name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build-docker-images:

    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@v3
      name: Log in to Docker Hub
    -
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER_NAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    -
      name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dragon_head:latest
    
