name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build-docker-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Docker hub
      run: docker login -u ${{DOCKER.DOCKER_HUB_SECRET}} -p ${{DOCKER.DOCKER_HUB_USER_NAME}}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag liliuli808/dragon_head:$(date +%s)
    
